import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {renderToStaticMarkup} from 'react-dom/server';
import {DitherIcon,definitions,studies,type Texture} from '../src';
import './style.css';
import {MotionStudies} from './MotionStudies';
const palettes = [
 {name:'Iris',dark:'#bea5f5',light:'#7048b4'},
 {name:'Cobalt',dark:'#92b5ff',light:'#315bc4'},
 {name:'Jade',dark:'#86d5b5',light:'#247458'},
 {name:'Amber',dark:'#eac282',light:'#956019'},
 {name:'Coral',dark:'#f2a08c',light:'#b44735'},
 {name:'Rose',dark:'#eba0c2',light:'#a73770'},
 {name:'Citron',dark:'#d0e99a',light:'#5a731e'},
 {name:'Graphite',dark:'#d2d6dc',light:'#424954'},
];
const componentName=(name:string)=>name.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join('')+'Icon';
function App(){
 const [palette,setPalette]=useState('Iris');
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All icons'),[selected,setSelected]=useState('bell'),[texture,setTexture]=useState<Texture>('dither'),[size,setSize]=useState(64),[dark,setDark]=useState(true),[motion,setMotion]=useState(true),[replay,setReplay]=useState(0),[toast,setToast]=useState(''),[format,setFormat]=useState('React');
 const colors=palettes.find(p=>p.name===palette)!;const color=dark?colors.dark:colors.light;
 const current=definitions.find(d=>d.name===selected)!;
 const visible=definitions.filter(d=>(category==='All icons'||d.category===category)&&`${d.name} ${d.category}`.includes(query.toLowerCase().trim()));
 const svg=renderToStaticMarkup(<DitherIcon name={selected} size={size} texture={texture} animate={motion} color={color}/>);
 const code=format==='React'?`import { ${componentName(selected)} } from '@unlocalhosted/dither-icons';\n\n<button className="di-trigger" aria-label="${selected}">\n  <${componentName(selected)} size={${size}} texture="${texture}" color="${color}" animate={${motion}} />\n</button>`:svg;
 async function copy(){try{await navigator.clipboard.writeText(code);setToast(`${format} copied`)}catch{setToast('Clipboard unavailable. Select and copy the code below.')}}
 function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download=`${selected}-${texture}.svg`;a.click();URL.revokeObjectURL(a.href);setToast('SVG downloaded');}
 return <div className="app" data-theme={dark?'dark':'light'} style={{'--accent':color,'--icon-color':color,'--accent-ink':dark?'#16141b':'#ffffff'} as React.CSSProperties}><header><a className="brand" href="#"><DitherIcon name="sparkles" size={27}/> dither<span>icons</span></a><nav><a href="#motion-studies">Motion studies</a><a href="#collection">Collection</a><a href="#use">Usage</a><button aria-label={dark?'Switch to light theme':'Switch to dark theme'} onClick={()=>setDark(!dark)}><DitherIcon name={dark?'sun':'moon'} size={20}/></button><span className="version">v0.1 / MIT</span></nav></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><i/> AN ICON LIBRARY BY UNLOCALHOSTED</div><h1>Fine grain.<br/><span>Quiet character.</span></h1><p>Considered shapes, rendered in grain. A collection of gently animated icons with a softer digital texture.</p><div className="hero-actions"><a className="primary" href="#collection">Explore 36 icons <span>↘</span></a><a href="/unlocalhosted-dither-icons-0.1.0.tgz" download className="package">Download React package ↗</a></div><div className="hero-meta">Precision contours <b>·</b> Original geometry <b>·</b> React + SVG</div></div><div className="specimen" aria-label="Dither icon specimen"><span className="spec-label">STUDY 001 — LIGHT, SHADE & GRAIN</span><div className="spec-art"><DitherIcon name="sparkles" size={208} texture={texture}/><div className="orbit one"><DitherIcon name="bolt" size={48}/></div><div className="orbit two"><DitherIcon name="heart" size={56}/></div><div className="orbit three"><DitherIcon name="layers" size={44}/></div></div><div className="spec-bottom"><span>ORDERED DITHER / DIRECTIONAL LIGHT</span><span>HOVER TO FEEL IT ↗</span></div></div></section>
 <section id="collection" className="collection"><div className="section-heading"><h2>The collection <span>036</span></h2><label className="motion-toggle"><input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/> Motion on hover</label></div><div className="toolbar"><label className="search"><DitherIcon name="search" size={18}/><input aria-label="Search icons" placeholder="Search icons…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</label><label className="palette-picker"><span className="color-dot"/><span className="sr-only">Primary color</span><select aria-label="Primary color" value={palette} onChange={e=>{setPalette(e.target.value);setToast('')}}>{palettes.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select></label><div className="textures" aria-label="Texture">{(['dither','solid','outline'] as const).map(t=><button key={t} aria-pressed={texture===t} onClick={()=>setTexture(t)}>{t}</button>)}</div></div><div className="categories">{['All icons','Interface','Navigation','Files','Communication','Media','Development'].map(c=><button key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}>{c}</button>)}</div>
 <MotionStudies texture={texture} enabled={motion}/>
 <div className="workspace"><div><div className="grid">{visible.map((d,i)=><button key={d.name} className="tile di-trigger" aria-label={`Inspect ${d.name}`} aria-pressed={selected===d.name} onClick={()=>{setSelected(d.name);setReplay(n=>n+1);setToast('')}}><span className="tile-index">{String(definitions.indexOf(d)+1).padStart(2,'0')}</span><DitherIcon name={d.name} size={size} texture={texture} animate={motion}/><span className="tile-name">{d.name}</span><span className="tile-add">↗</span></button>)}</div>{visible.length===0&&<div className="empty"><DitherIcon name="search" size={48}/><h3>No icons found</h3><p>Try “arrow”, “file”, or another category.</p><button onClick={()=>{setQuery('');setCategory('All icons')}}>Reset filters</button></div>}<div className="grid-foot">{visible.length} icons <span>Hover to animate. Select to inspect.</span></div></div>
 <aside className="inspector" aria-label="Icon inspector"><div className="inspector-title"><span>{selected}</span><span className="tag">SVG</span></div><button disabled={!motion} className="large-preview di-trigger" aria-label={`Replay ${selected} animation`} onClick={()=>setReplay(n=>n+1)}><DitherIcon key={selected} name={selected} replayKey={replay} size={144} texture={texture} animate={motion} active={motion&&replay>0}/><span>↻ Replay animation</span></button><p className="description">{studies[selected]?.caption??current.description}</p><div className="size-row"><span>Preview size</span><div>{[24,32,48,64].map(s=><button key={s} aria-label={`${s} pixel icons`} aria-pressed={size===s} onClick={()=>setSize(s)}>{s}</button>)}</div></div><div className="code-tabs">{['React','SVG'].map(f=><button aria-pressed={format===f} key={f} onClick={()=>setFormat(f)}>{f}</button>)}<button className="copy" onClick={copy}>Copy {format} ⧉</button></div><pre tabIndex={0}><code>{code}</code></pre><button className="download" onClick={download}><DitherIcon name="download" size={18}/> Download SVG</button><p role="status" className="status">{toast||`${palette} · Transparent background`}</p></aside></div></section>
 <section className="usage" id="use"><div><div className="eyebrow">BUILT TO LEAVE THIS PAGE</div><h2>A little texture.<br/>A lighter touch.</h2><p>Use named React components or take the SVG directly. Native browser motion, no animation dependency, no icon font.</p><a href="/unlocalhosted-dither-icons-0.1.0.tgz" download>Download local package ↗</a></div><div className="steps"><article><span>01</span><div><h3>Install the download</h3><code>npm install ./unlocalhosted-dither-icons-0.1.0.tgz</code><p>Local package preview. Not published to npm yet.</p></div></article><article><span>02</span><div><h3>Make the whole button respond</h3><p>Add <code>di-trigger</code> to your button. Hover and keyboard focus play the icon once. Use <code>animate={'{false}'}</code> for a still icon.</p></div></article><article><span>03</span><div><h3>Keep it readable</h3><p>Use solid or outline at small sizes. Dither comes alive at 48px and above. Choose a palette to carry its color into your exports. Reduced-motion preferences are respected automatically.</p></div></article></div></section></main><footer><span>dither icons / Unlocalhosted</span><span>36 originals. One shared language.</span><a href="https://lucide-animated.com/" target="_blank" rel="noreferrer">Interaction inspiration: lucide-animated ↗</a></footer></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
