import {useState} from 'react';
import {DitherIcon,studies,definitions,type Texture} from '../src';
const SETS:Record<string,string[]>={'Platform / 08':['save-preferences','file-explorer','expand-view','sign-out'],'Platform / 07':['tokenize','embedding-lookup','attention-focus','batch-sampling'],'Platform / 06':['learning-rhythm','gradient-check','experiment-compare','training-step'],'Platform / 05':['code-run','test-suite','milestone','concept-review'],'Platform / 04':['sigma','bug','sliders','graduation-cap'],'Platform / 03':['workspace','gauge','orbit','lifebuoy'],'Platform / 02':['tensor','network','checkpoint','hint'],'Platform / 01':['path','flask','target','retry'],'Refinement / 04':['play','pause','volume','code'],'Refinement / 03':['book','mail','message','send'],'Refinement / 02':['folder','file','copy','trash'],'Refinement / 01':['arrow-right','arrow-up','external-link','upload'],Foundation:['bell','heart','download','layers'],Navigation:['arrow-right','arrow-up','external-link'],'Files / transfer':['upload','copy','file'],'Files / containers':['folder','trash','book'],Communication:['mail','message','send'],Media:['play','pause','volume'],Development:['code','terminal','cpu','chart'],'Interface / places':['search','home','settings'],'Interface / actions':['check','close','plus'],'Interface / presence':['user','lock','eye'],'Interface / light':['sparkles','sun','moon','bolt']};
export function MotionStudies({texture,enabled}:{texture:Texture;enabled:boolean}){
 const [set,setSet]=useState('Platform / 08');
 const ORDER=SETS[set].filter(name=>studies[name]);
 const [speed,setSpeed]=useState(1),[replay,setReplay]=useState(0),[progress,setProgress]=useState<number|undefined>();
 return <section className="motion-studies" id="motion-studies" aria-labelledby="studies-heading">
  <div className="studies-heading"><div><span className="eyebrow">MOTION STUDIES</span><h2 id="studies-heading">Small gestures. A little soul.</h2></div><div className="study-controls"><select aria-label="Study family" value={set} onChange={e=>{setSet(e.target.value);setProgress(undefined);setReplay(0)}}>{Object.keys(SETS).map(name=><option key={name}>{name}</option>)}</select><label><span className="sr-only">Playback speed</span><select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>Actual speed</option><option value={.5}>Half speed</option></select></label><button disabled={!enabled} aria-pressed={progress!==undefined} onClick={()=>setProgress(progress===undefined?0:undefined)}>Inspect timing</button><button onClick={()=>{setProgress(undefined);setReplay(n=>n+1)}} disabled={!enabled}>↻ Replay set</button></div></div>
  {progress!==undefined&&<label className="study-timeline"><span>Rest</span><input type="range" disabled={!enabled} aria-label="Motion timeline" min="0" max="100" value={Math.round(progress*100)} onChange={e=>setProgress(Number(e.target.value)/100)}/><span>Settle</span><output>{Math.round(progress*100)}%</output></label>}
  <div className="study-grid">{ORDER.map((name,index)=><article className="study" key={name}>
   <button disabled={!enabled} className="study-stage di-trigger" aria-label={`Play ${name} study`} style={{'--study-time':`${studies[name].duration/speed}ms`} as React.CSSProperties}>
    <span className="study-number">0{index+1}</span><span className="study-play">↻</span>
    <DitherIcon name={name} size={112} texture={texture} animate={enabled} speed={speed} replayKey={replay} progress={progress}/>
    <span className="study-progress"/>
   </button><div className="study-copy"><h3>{definitions.find(d=>d.name===name)?.label??name}</h3><p>{studies[name].caption}</p><div className="study-beats">{studies[name].stages.map((stage,i)=><span key={stage}><small>{i+1}</small>{stage}</span>)}</div></div>
  </article>)}</div><p className="study-hint">Hover, focus, or tap to play. Each gesture finishes before another begins.</p>
 </section>
}
